name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.USERNAME }}/simple-web-api-gh:latest
    
    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.USERNAME }}/simple-web-api-gh:latest
      
    - name: Clean up
      run: docker logout
      if: always() # Se ejecutará incluso si un paso anterior falla

 
   
